---
title: "visualization"
author: "Nelson Gaillard"
date: "2025-09-25"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)
library(ggridges)
library(p8105.datasets)
```

Import the weather data

```{r}
data("weather_df")
```

Making our first plot :-)

```{r}
ggplot(weather_df, mapping = aes(x = tmin, y = tmax)) +
  geom_point()
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax))+
  geom_point()
```

```{r}
ggp_weather_scatterplot = 
  weather_df |>
    ggplot(aes(x = tmin, y = tmax))+
    geom_point()

ggp_weather_scatterplot
```

```{r}
weather_df |>
  filter(is.na(tmax))
```


## Fancier scatterplots!

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.3) +
  geom_smooth(se = FALSE)
```

Where you define aestherics can matter

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(aes(color = name, size = prcp), alpha = 0.3) +
  geom_smooth(se = FALSE, size = 0.6)
```

use faceting real quick

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(aes(color = name), alpha = 0.3, size = 0.8) +
  geom_smooth(se = FALSE, size = 0.6) +
  facet_grid(. ~ name)

weather_df |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(aes(color = name), alpha = 0.3, size = 0.8) +
  geom_smooth(se = FALSE, size = 0.6) +
  facet_grid(name ~ .)
```



